[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dotkeep"
version = "0.1.0"
description = "dotkeep is a minimal, Git-backed dotfiles manager for Linux"
requires-python = ">=3.8"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}

authors = [
  {name = "Moustafa Salem", email = "salemmoustafa442@gmail.com"}
]

dependencies = [
  "typer",
  "gitpython"
]

[project.scripts]
dotkeep = "cli:app"

[tool.setuptools]
package-dir = {"" = "src"}
